/* ###########################################################################
    EGHV : Enhanced Goodies and Hostile Villagers for Civilization VI
    Copyright (c) 2020-2023 zzragnar0kzz
    All rights reserved.
########################################################################### */

/* ###########################################################################
    begin EGHV frontend configuration
########################################################################### */

-- configure the StandardGoodyHuts transition table
REPLACE INTO EGHV_StandardGoodyHuts (GoodyHut, Name, SubTypeGoodyHut, Description, Icon, SortIndex)
VALUES
    -- abilities type
    ('GOODYHUT_ABILITIES', 'LOC_EGHV_GOODYHUT_IMPROVED_SIGHT_NAME', 'GOODYHUT_IMPROVED_SIGHT', 'LOC_EGHV_GOODYHUT_IMPROVED_SIGHT_DESC', 'ICON_EGHV_IMPROVED_SIGHT', 100),
    ('GOODYHUT_ABILITIES', 'LOC_EGHV_GOODYHUT_IMPROVED_HEALING_NAME', 'GOODYHUT_IMPROVED_HEALING', 'LOC_EGHV_GOODYHUT_IMPROVED_HEALING_DESC', 'ICON_EGHV_IMPROVED_HEALING', 200),
    ('GOODYHUT_ABILITIES', 'LOC_EGHV_GOODYHUT_IMPROVED_MOVEMENT_NAME', 'GOODYHUT_IMPROVED_MOVEMENT', 'LOC_EGHV_GOODYHUT_IMPROVED_MOVEMENT_DESC', 'ICON_EGHV_IMPROVED_MOVEMENT', 300),
    ('GOODYHUT_ABILITIES', 'LOC_EGHV_GOODYHUT_IMPROVED_STRENGTH_NAME', 'GOODYHUT_IMPROVED_STRENGTH', 'LOC_EGHV_GOODYHUT_IMPROVED_STRENGTH_DESC', 'ICON_EGHV_IMPROVED_STRENGTH', 400),
    -- civics type
    ('GOODYHUT_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_BOOST_NAME', 'GOODYHUT_ONE_CIVIC_BOOST', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_BOOST_DESC', 'ICON_EGHV_ONE_CIVIC_BOOST', 100),
    ('GOODYHUT_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVIC_BOOSTS_NAME', 'GOODYHUT_TWO_CIVIC_BOOSTS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVIC_BOOSTS_DESC', 'ICON_EGHV_TWO_CIVIC_BOOSTS', 200),
    ('GOODYHUT_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_NAME', 'GOODYHUT_ONE_CIVIC', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_DESC', 'ICON_EGHV_ONE_CIVIC', 300),
    ('GOODYHUT_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVICS_NAME', 'GOODYHUT_TWO_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVICS_DESC', 'ICON_EGHV_TWO_CIVICS', 400),
    -- culture type
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_SMALL_CULTURE_NAME', 'GOODYHUT_SMALL_CULTURE', 'LOC_EGHV_GOODYHUT_SMALL_CULTURE_DESC', 'ICON_EGHV_SMALL_CULTURE', 100),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_MEDIUM_CULTURE_NAME', 'GOODYHUT_MEDIUM_CULTURE', 'LOC_EGHV_GOODYHUT_MEDIUM_CULTURE_DESC', 'ICON_EGHV_MEDIUM_CULTURE', 200),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_LARGE_CULTURE_NAME', 'GOODYHUT_LARGE_CULTURE', 'LOC_EGHV_GOODYHUT_LARGE_CULTURE_DESC', 'ICON_EGHV_LARGE_CULTURE', 300),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_HUGE_CULTURE_NAME', 'GOODYHUT_HUGE_CULTURE', 'LOC_EGHV_GOODYHUT_HUGE_CULTURE_DESC', 'ICON_EGHV_HUGE_CULTURE', 400),
    -- envoys type
    ('GOODYHUT_ENVOYS', 'LOC_EGHV_GOODYHUT_ONE_ENVOY_NAME', 'GOODYHUT_ONE_ENVOY', 'LOC_EGHV_GOODYHUT_ONE_ENVOY_DESC', 'ICON_EGHV_ONE_ENVOY', 100),
    ('GOODYHUT_ENVOYS', 'LOC_EGHV_GOODYHUT_TWO_ENVOYS_NAME', 'GOODYHUT_TWO_ENVOYS', 'LOC_EGHV_GOODYHUT_TWO_ENVOYS_DESC', 'ICON_EGHV_TWO_ENVOYS', 200),
    ('GOODYHUT_ENVOYS', 'LOC_EGHV_GOODYHUT_THREE_ENVOYS_NAME', 'GOODYHUT_THREE_ENVOYS', 'LOC_EGHV_GOODYHUT_THREE_ENVOYS_DESC', 'ICON_EGHV_THREE_ENVOYS', 300),
    ('GOODYHUT_ENVOYS', 'LOC_EGHV_GOODYHUT_FOUR_ENVOYS_NAME', 'GOODYHUT_FOUR_ENVOYS', 'LOC_EGHV_GOODYHUT_FOUR_ENVOYS_DESC', 'ICON_EGHV_FOUR_ENVOYS', 400),
    -- faith type
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_SUM_NAME', 'GOODYHUT_SMALL_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_SUM_DESC', 'ICON_EGHV_SMALL_FAITH', 100),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_MEDIUM_SUM_NAME', 'GOODYHUT_MEDIUM_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_MEDIUM_SUM_DESC', 'ICON_EGHV_MEDIUM_FAITH', 200),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_LARGE_SUM_NAME', 'GOODYHUT_LARGE_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_LARGE_SUM_DESC', 'ICON_EGHV_LARGE_FAITH', 300),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_ONE_RELIC_NAME', 'GOODYHUT_ONE_RELIC', 'LOC_EGHV_GOODYHUT_FAITH_ONE_RELIC_DESC', 'ICON_EGHV_ONE_RELIC', 400),
    -- gold type
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_SUM_NAME', 'GOODYHUT_SMALL_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_SUM_DESC', 'ICON_EGHV_SMALL_GOLD', 100),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_MEDIUM_SUM_NAME', 'GOODYHUT_MEDIUM_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_MEDIUM_SUM_DESC', 'ICON_EGHV_MEDIUM_GOLD', 200),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_LARGE_SUM_NAME', 'GOODYHUT_LARGE_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_LARGE_SUM_DESC', 'ICON_EGHV_LARGE_GOLD', 300),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_ADD_TRADE_ROUTE_NAME', 'GOODYHUT_ADD_TRADE_ROUTE', 'LOC_EGHV_GOODYHUT_GOLD_ADD_TRADE_ROUTE_DESC', 'ICON_EGHV_ADD_TRADE_ROUTE', 400),
    -- goodyhuts type
    ('GOODYHUT_GOODYHUTS', 'LOC_EGHV_GOODYHUT_ONE_GOODYHUT_NAME', 'GOODYHUT_ONE_GOODYHUT', 'LOC_EGHV_GOODYHUT_ONE_GOODYHUT_DESC', 'ICON_EGHV_ONE_GOODYHUT', 100),
    ('GOODYHUT_GOODYHUTS', 'LOC_EGHV_GOODYHUT_TWO_GOODYHUTS_NAME', 'GOODYHUT_TWO_GOODYHUTS', 'LOC_EGHV_GOODYHUT_TWO_GOODYHUTS_DESC', 'ICON_EGHV_TWO_GOODYHUTS', 200),
    ('GOODYHUT_GOODYHUTS', 'LOC_EGHV_GOODYHUT_THREE_GOODYHUTS_NAME', 'GOODYHUT_THREE_GOODYHUTS', 'LOC_EGHV_GOODYHUT_THREE_GOODYHUTS_DESC', 'ICON_EGHV_THREE_GOODYHUTS', 300),
    ('GOODYHUT_GOODYHUTS', 'LOC_EGHV_GOODYHUT_FOUR_GOODYHUTS_NAME', 'GOODYHUT_FOUR_GOODYHUTS', 'LOC_EGHV_GOODYHUT_FOUR_GOODYHUTS_DESC', 'ICON_EGHV_FOUR_GOODYHUTS', 400),
    -- great people type
    -- hostiles type
    ('GOODYHUT_HOSTILES', 'LOC_EGHV_GOODYHUT_LOW_HOSTILITY_VILLAGERS_NAME', 'GOODYHUT_LOW_HOSTILITY_VILLAGERS', 'LOC_EGHV_GOODYHUT_LOW_HOSTILITY_VILLAGERS_DESC', 'ICON_EGHV_LOW_HOSTILITY_VILLAGERS', 100),
    ('GOODYHUT_HOSTILES', 'LOC_EGHV_GOODYHUT_MID_HOSTILITY_VILLAGERS_NAME', 'GOODYHUT_MID_HOSTILITY_VILLAGERS', 'LOC_EGHV_GOODYHUT_MID_HOSTILITY_VILLAGERS_DESC', 'ICON_EGHV_MID_HOSTILITY_VILLAGERS', 200),
    ('GOODYHUT_HOSTILES', 'LOC_EGHV_GOODYHUT_HIGH_HOSTILITY_VILLAGERS_NAME', 'GOODYHUT_HIGH_HOSTILITY_VILLAGERS', 'LOC_EGHV_GOODYHUT_HIGH_HOSTILITY_VILLAGERS_DESC', 'ICON_EGHV_HIGH_HOSTILITY_VILLAGERS', 300),
    ('GOODYHUT_HOSTILES', 'LOC_EGHV_GOODYHUT_MAX_HOSTILITY_VILLAGERS_NAME', 'GOODYHUT_MAX_HOSTILITY_VILLAGERS', 'LOC_EGHV_GOODYHUT_MAX_HOSTILITY_VILLAGERS_DESC', 'ICON_EGHV_MAX_HOSTILITY_VILLAGERS', 400),
    -- military type
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SCOUT_NAME', 'GOODYHUT_GRANT_SCOUT', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SCOUT_DESC', 'ICON_EGHV_GRANT_RECON', 100),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SLINGER_NAME', 'GOODYHUT_GRANT_SLINGER', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SLINGER_DESC', 'ICON_EGHV_GRANT_RANGED', 200),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_WARRIOR_NAME', 'GOODYHUT_GRANT_WARRIOR', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_WARRIOR_DESC', 'ICON_EGHV_GRANT_MELEE', 200),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SPEARMAN_NAME', 'GOODYHUT_GRANT_SPEARMAN', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SPEARMAN_DESC', 'ICON_EGHV_GRANT_ANTI_CAVALRY', 200),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HEAVY_CHARIOT_NAME', 'GOODYHUT_GRANT_HEAVY_CHARIOT', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HEAVY_CHARIOT_DESC', 'ICON_EGHV_GRANT_HEAVY_CAVALRY', 300),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HORSEMAN_NAME', 'GOODYHUT_GRANT_HORSEMAN', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HORSEMAN_DESC', 'ICON_EGHV_GRANT_LIGHT_CAVALRY', 300),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_BATTERING_RAM_NAME', 'GOODYHUT_GRANT_BATTERING_RAM', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_BATTERING_RAM_DESC', 'ICON_EGHV_GRANT_SUPPORT', 400),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_CATAPULT_NAME', 'GOODYHUT_GRANT_CATAPULT', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_CATAPULT_DESC', 'ICON_EGHV_GRANT_SIEGE', 400),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MILITARY_ENGINEER_NAME', 'GOODYHUT_GRANT_MILITARY_ENGINEER', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MILITARY_ENGINEER_DESC', 'ICON_EGHV_GRANT_MILITARY_ENGINEER', 500),
    -- policies type
    ('GOODYHUT_POLICIES', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_MILITARY_SLOT_NAME', 'GOODYHUT_ONE_MILITARY_SLOT', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_MILITARY_SLOT_DESC', 'ICON_EGHV_MILITARY_POLICY_SLOT', 500),
    ('GOODYHUT_POLICIES', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_ECONOMIC_SLOT_NAME', 'GOODYHUT_ONE_ECONOMIC_SLOT', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_ECONOMIC_SLOT_DESC', 'ICON_EGHV_ECONOMIC_POLICY_SLOT', 500),
    ('GOODYHUT_POLICIES', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_DIPLOMATIC_SLOT_NAME', 'GOODYHUT_ONE_DIPLOMATIC_SLOT', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_DIPLOMATIC_SLOT_DESC', 'ICON_EGHV_DIPLOMATIC_POLICY_SLOT', 500),
    ('GOODYHUT_POLICIES', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_WILDCARD_SLOT_NAME', 'GOODYHUT_ONE_WILDCARD_SLOT', 'LOC_EGHV_GOODYHUT_POLICIES_ONE_WILDCARD_SLOT_DESC', 'ICON_EGHV_WILDCARD_POLICY_SLOT', 500),
    -- promotions type
    ('GOODYHUT_PROMOTIONS', 'LOC_EGHV_GOODYHUT_SMALL_EXPERIENCE_NAME', 'GOODYHUT_SMALL_EXPERIENCE', 'LOC_EGHV_GOODYHUT_SMALL_EXPERIENCE_DESC', 'ICON_EGHV_SMALL_EXPERIENCE', 100),
    ('GOODYHUT_PROMOTIONS', 'LOC_EGHV_GOODYHUT_MEDIUM_EXPERIENCE_NAME', 'GOODYHUT_MEDIUM_EXPERIENCE', 'LOC_EGHV_GOODYHUT_MEDIUM_EXPERIENCE_DESC', 'ICON_EGHV_MEDIUM_EXPERIENCE', 200),
    ('GOODYHUT_PROMOTIONS', 'LOC_EGHV_GOODYHUT_LARGE_EXPERIENCE_NAME', 'GOODYHUT_LARGE_EXPERIENCE', 'LOC_EGHV_GOODYHUT_LARGE_EXPERIENCE_DESC', 'ICON_EGHV_LARGE_EXPERIENCE', 300),
    ('GOODYHUT_PROMOTIONS', 'LOC_EGHV_GOODYHUT_HUGE_EXPERIENCE_NAME', 'GOODYHUT_HUGE_EXPERIENCE', 'LOC_EGHV_GOODYHUT_HUGE_EXPERIENCE_DESC', 'ICON_EGHV_HUGE_EXPERIENCE', 400),
    ('GOODYHUT_PROMOTIONS', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_UPGRADE_NAME', 'GOODYHUT_GRANT_UPGRADE', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_UPGRADE_DESC', 'ICON_EGHV_UPGRADE_UNIT', 500),
    -- science type
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SMALL_SCIENCE_NAME', 'GOODYHUT_SMALL_SCIENCE', 'LOC_EGHV_GOODYHUT_SMALL_SCIENCE_DESC', 'ICON_EGHV_SMALL_SCIENCE', 100),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_MEDIUM_SCIENCE_NAME', 'GOODYHUT_MEDIUM_SCIENCE', 'LOC_EGHV_GOODYHUT_MEDIUM_SCIENCE_DESC', 'ICON_EGHV_MEDIUM_SCIENCE', 200),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_LARGE_SCIENCE_NAME', 'GOODYHUT_LARGE_SCIENCE', 'LOC_EGHV_GOODYHUT_LARGE_SCIENCE_DESC', 'ICON_EGHV_LARGE_SCIENCE', 300),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_HUGE_SCIENCE_NAME', 'GOODYHUT_HUGE_SCIENCE', 'LOC_EGHV_GOODYHUT_HUGE_SCIENCE_DESC', 'ICON_EGHV_HUGE_SCIENCE', 400),
    -- secrets type
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_AMENITIES_NAME', 'GOODYHUT_VILLAGER_SECRETS_AMENITIES', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_AMENITIES_DESC', 'ICON_EGHV_TOTEM_AMENITIES', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_CULTURE_NAME', 'GOODYHUT_VILLAGER_SECRETS_CULTURE', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_CULTURE_DESC', 'ICON_EGHV_TOTEM_CULTURE', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_FAITH_NAME', 'GOODYHUT_VILLAGER_SECRETS_FAITH', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_FAITH_DESC', 'ICON_EGHV_TOTEM_FAITH', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_FOOD_NAME', 'GOODYHUT_VILLAGER_SECRETS_FOOD', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_FOOD_DESC', 'ICON_EGHV_TOTEM_FOOD', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_GOLD_NAME', 'GOODYHUT_VILLAGER_SECRETS_GOLD', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_GOLD_DESC', 'ICON_EGHV_TOTEM_GOLD', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_PRODUCTION_NAME', 'GOODYHUT_VILLAGER_SECRETS_PRODUCTION', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_PRODUCTION_DESC', 'ICON_EGHV_TOTEM_PRODUCTION', 500),
    ('GOODYHUT_SECRETS', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_SCIENCE_NAME', 'GOODYHUT_VILLAGER_SECRETS_SCIENCE', 'LOC_EGHV_GOODYHUT_VILLAGER_SECRETS_SCIENCE_DESC', 'ICON_EGHV_TOTEM_SCIENCE', 500),
    -- survivors type
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_ADD_POP_NAME', 'GOODYHUT_ADD_POP', 'LOC_EGHV_GOODYHUT_SURVIVORS_ADD_POP_DESC', 'ICON_EGHV_ADD_POP', 100),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_BUILDER_NAME', 'GOODYHUT_GRANT_BUILDER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_BUILDER_DESC', 'ICON_EGHV_GRANT_BUILDER', 200),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_TRADER_NAME', 'GOODYHUT_GRANT_TRADER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_TRADER_DESC', 'ICON_EGHV_GRANT_TRADER', 300),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_SETTLER_NAME', 'GOODYHUT_GRANT_SETTLER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_SETTLER_DESC', 'ICON_EGHV_GRANT_SETTLER', 400),
    -- techs type
    ('GOODYHUT_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_BOOST_NAME', 'GOODYHUT_ONE_TECH_BOOST', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_BOOST_DESC', 'ICON_EGHV_ONE_TECH_BOOST', 100),
    ('GOODYHUT_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECH_BOOSTS_NAME', 'GOODYHUT_TWO_TECH_BOOSTS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECH_BOOSTS_DESC', 'ICON_EGHV_TWO_TECH_BOOSTS', 200),
    ('GOODYHUT_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_NAME', 'GOODYHUT_ONE_TECH', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_DESC', 'ICON_EGHV_ONE_TECH', 300),
    ('GOODYHUT_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECHS_NAME', 'GOODYHUT_TWO_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECHS_DESC', 'ICON_EGHV_TWO_TECHS', 400);

-- configure the Goody Hut picker for Standard ruleset
REPLACE INTO TribalVillages SELECT * FROM EGHV_StandardGoodyHuts;

/* ###########################################################################
    end EGHV frontend configuration
########################################################################### */
