/* ###########################################################################
    EGHV : Enhanced Goodies and Hostile Villagers for Civilization VI
    Copyright (c) 2020-2021 zzragnar0kzz
    All rights reserved.
########################################################################### */

/* ###########################################################################
    begin EGHV frontend configuration
########################################################################### */

-- configure the StandardGoodyHuts transition table
REPLACE INTO EGHV_StandardGoodyHuts (GoodyHut, Name, SubTypeGoodyHut, Description, Icon)
VALUES
    -- culture type
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_SMALL_MODIFIER_DESC', 'ICON_CITYSTATE_CULTURE'),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_SMALL_CHANGE_DESC', 'ICON_CITYSTATE_CULTURE'),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVICS_NAME', 'GOODYHUT_TWO_CIVICS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVICS_DESC', 'ICON_CITYSTATE_CULTURE'),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_NAME', 'GOODYHUT_ONE_CIVIC', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_DESC', 'ICON_CITYSTATE_CULTURE'),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVIC_BOOSTS_NAME', 'GOODYHUT_TWO_CIVIC_BOOSTS', 'LOC_EGHV_GOODYHUT_CULTURE_TWO_CIVIC_BOOSTS_DESC', 'ICON_CITYSTATE_CULTURE'),
    ('GOODYHUT_CULTURE', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_BOOST_NAME', 'GOODYHUT_ONE_CIVIC_BOOST', 'LOC_EGHV_GOODYHUT_CULTURE_ONE_CIVIC_BOOST_DESC', 'ICON_CITYSTATE_CULTURE'),
    -- faith type
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_MODIFIER_DESC', 'ICON_CITYSTATE_FAITH'),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_CHANGE_DESC', 'ICON_CITYSTATE_FAITH'),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_ONE_RELIC_NAME', 'GOODYHUT_ONE_RELIC', 'LOC_EGHV_GOODYHUT_FAITH_ONE_RELIC_DESC', 'ICON_CITYSTATE_FAITH'),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_LARGE_SUM_NAME', 'GOODYHUT_LARGE_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_LARGE_SUM_DESC', 'ICON_CITYSTATE_FAITH'),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_MEDIUM_SUM_NAME', 'GOODYHUT_MEDIUM_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_MEDIUM_SUM_DESC', 'ICON_CITYSTATE_FAITH'),
    ('GOODYHUT_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_SUM_NAME', 'GOODYHUT_SMALL_FAITH', 'LOC_EGHV_GOODYHUT_FAITH_SMALL_SUM_DESC', 'ICON_CITYSTATE_FAITH'),
    -- gold type
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_MODIFIER_DESC', 'ICON_YIELD_GOLD_5'),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_CHANGE_DESC', 'ICON_YIELD_GOLD_5'),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_ADD_TRADE_ROUTE_NAME', 'GOODYHUT_ADD_TRADE_ROUTE', 'LOC_EGHV_GOODYHUT_GOLD_ADD_TRADE_ROUTE_DESC', 'ICON_YIELD_GOLD_4'),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_LARGE_SUM_NAME', 'GOODYHUT_LARGE_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_LARGE_SUM_DESC', 'ICON_YIELD_GOLD_3'),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_MEDIUM_SUM_NAME', 'GOODYHUT_MEDIUM_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_MEDIUM_SUM_DESC', 'ICON_YIELD_GOLD_2'),
    ('GOODYHUT_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_SUM_NAME', 'GOODYHUT_SMALL_GOLD', 'LOC_EGHV_GOODYHUT_GOLD_SMALL_SUM_DESC', 'ICON_YIELD_GOLD_1'),
    -- military type
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_PRODUCTION_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_PRODUCTION', 'LOC_EGHV_GOODYHUT_PRODUCTION_SMALL_MODIFIER_DESC', 'ICON_YIELD_PRODUCTION_5'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_PRODUCTION_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_PRODUCTION', 'LOC_EGHV_GOODYHUT_PRODUCTION_SMALL_CHANGE_DESC', 'ICON_YIELD_PRODUCTION_5'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MEDIC_NAME', 'GOODYHUT_GRANT_MEDIC', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MEDIC_DESC', 'ICON_YIELD_PRODUCTION_5'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MILITARY_ENGINEER_NAME', 'GOODYHUT_GRANT_MILITARY_ENGINEER', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_MILITARY_ENGINEER_DESC', 'ICON_YIELD_PRODUCTION_5'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HEAVY_CHARIOT_NAME', 'GOODYHUT_GRANT_HEAVY_CHARIOT', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HEAVY_CHARIOT_DESC', 'ICON_YIELD_PRODUCTION_4'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HORSEMAN_NAME', 'GOODYHUT_GRANT_HORSEMAN', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_HORSEMAN_DESC', 'ICON_YIELD_PRODUCTION_4'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SPEARMAN_NAME', 'GOODYHUT_GRANT_SPEARMAN', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SPEARMAN_DESC', 'ICON_YIELD_PRODUCTION_3'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SLINGER_NAME', 'GOODYHUT_GRANT_SLINGER', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SLINGER_DESC', 'ICON_YIELD_PRODUCTION_3'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_WARRIOR_NAME', 'GOODYHUT_GRANT_WARRIOR', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_WARRIOR_DESC', 'ICON_YIELD_PRODUCTION_2'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SCOUT_NAME', 'GOODYHUT_GRANT_SCOUT', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_SCOUT_DESC', 'ICON_YIELD_PRODUCTION_2'),
    ('GOODYHUT_MILITARY', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_EXPERIENCE_NAME', 'GOODYHUT_GRANT_EXPERIENCE', 'LOC_EGHV_GOODYHUT_MILITARY_GRANT_EXPERIENCE_DESC', 'ICON_YIELD_PRODUCTION_1'),
    -- science type
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_SMALL_MODIFIER_DESC', 'ICON_YIELD_SCIENCE_5'),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_SMALL_CHANGE_DESC', 'ICON_YIELD_SCIENCE_5'),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECHS_NAME', 'GOODYHUT_TWO_TECHS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECHS_DESC', 'ICON_YIELD_SCIENCE_4'),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_NAME', 'GOODYHUT_ONE_TECH', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_DESC', 'ICON_YIELD_SCIENCE_3'),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECH_BOOSTS_NAME', 'GOODYHUT_TWO_TECH_BOOSTS', 'LOC_EGHV_GOODYHUT_SCIENCE_TWO_TECH_BOOSTS_DESC', 'ICON_YIELD_SCIENCE_2'),
    ('GOODYHUT_SCIENCE', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_BOOST_NAME', 'GOODYHUT_ONE_TECH_BOOST', 'LOC_EGHV_GOODYHUT_SCIENCE_ONE_TECH_BOOST_DESC', 'ICON_YIELD_SCIENCE_1'),
    -- survivors type
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_FOOD_SMALL_MODIFIER_NAME', 'GOODYHUT_SMALL_MODIFIER_FOOD', 'LOC_EGHV_GOODYHUT_FOOD_SMALL_MODIFIER_DESC', 'ICON_YIELD_FOOD_5'),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_FOOD_SMALL_CHANGE_NAME', 'GOODYHUT_SMALL_CHANGE_FOOD', 'LOC_EGHV_GOODYHUT_FOOD_SMALL_CHANGE_DESC', 'ICON_YIELD_FOOD_5'),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_SETTLER_NAME', 'GOODYHUT_GRANT_SETTLER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_SETTLER_DESC', 'ICON_YIELD_FOOD_4'),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_TRADER_NAME', 'GOODYHUT_GRANT_TRADER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_TRADER_DESC', 'ICON_YIELD_FOOD_3'),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_BUILDER_NAME', 'GOODYHUT_GRANT_BUILDER', 'LOC_EGHV_GOODYHUT_SURVIVORS_GRANT_BUILDER_DESC', 'ICON_YIELD_FOOD_2'),
    ('GOODYHUT_SURVIVORS', 'LOC_EGHV_GOODYHUT_SURVIVORS_ADD_POP_NAME', 'GOODYHUT_ADD_POP', 'LOC_EGHV_GOODYHUT_SURVIVORS_ADD_POP_DESC', 'ICON_YIELD_FOOD_1'),
    --  EGHV : hostiles type
    ('GOODYHUT_HOSTILES', 'LOC_EGHV_GOODYHUT_SPAWN_HOSTILE_VILLAGERS_NAME', 'GOODYHUT_SPAWN_HOSTILE_VILLAGERS', 'LOC_EGHV_GOODYHUT_SPAWN_HOSTILE_VILLAGERS_DESC', 'ICON_CIVILIZATION_BARBARIAN');

-- configure the Goody Hut picker for Standard ruleset
INSERT INTO TribalVillages SELECT * FROM EGHV_StandardGoodyHuts;

/* ###########################################################################
    end EGHV frontend configuration
########################################################################### */
