/* ###########################################################################
    EGHV : Enhanced Goodies and Hostile Villagers for Civilization VI
    Copyright (c) 2020-2023 zzragnar0kzz
    All rights reserved.
########################################################################### */

/* ###########################################################################
    Begin EGHV ingame configuration
########################################################################### */

-- new Types
REPLACE INTO Types
    (Type, Kind)
VALUES
    -- enhanced healing unit ability
    ('ABILITY_IMPROVED_HEALING', 'KIND_ABILITY'),
    -- enhanced movement unit ability
    ('ABILITY_IMPROVED_MOVEMENT', 'KIND_ABILITY'),
    -- enhanced sight unit ability
    ('ABILITY_IMPROVED_SIGHT', 'KIND_ABILITY'),
    -- enhanced combat strength unit ability
    ('ABILITY_IMPROVED_STRENGTH', 'KIND_ABILITY'),
    -- Secrets : amenities villager totem
    ('BUILDING_AMENITIES_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_AMENITIES_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_AMENITIES_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : culture villager totem
    ('BUILDING_CULTURE_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_CULTURE_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_CULTURE_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : faith villager totem
    ('BUILDING_FAITH_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_FAITH_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_FAITH_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : food villager totem
    ('BUILDING_FOOD_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_FOOD_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_FOOD_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : gold villager totem
    ('BUILDING_GOLD_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_GOLD_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_GOLD_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : production villager totem
    ('BUILDING_PRODUCTION_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_PRODUCTION_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_PRODUCTION_TOTEM_BIG', 'KIND_BUILDING'),
    -- Secrets : science villager totem
    ('BUILDING_SCIENCE_TOTEM_LOCKED', 'KIND_BUILDING'),
    ('BUILDING_SCIENCE_TOTEM', 'KIND_BUILDING'),
    ('BUILDING_SCIENCE_TOTEM_BIG', 'KIND_BUILDING'),
    -- unit abilities
    ('GOODYHUT_ABILITIES', 'KIND_GOODY_HUT'),
    -- civic boosts and grants
    ('GOODYHUT_CIVICS', 'KIND_GOODY_HUT'),
    -- free Envoys
    ('GOODYHUT_ENVOYS', 'KIND_GOODY_HUT'),
    -- new Goody Hut spawns
    ('GOODYHUT_GOODYHUTS', 'KIND_GOODY_HUT'),
    -- Hostile Villagers "rewards"
    ('GOODYHUT_HOSTILES', 'KIND_GOODY_HUT'),
    -- policy slots
    ('GOODYHUT_POLICIES', 'KIND_GOODY_HUT'),
    -- unit experience and upgrades
    ('GOODYHUT_PROMOTIONS', 'KIND_GOODY_HUT'),
    -- Villager Totem buildings
    ('GOODYHUT_SECRETS', 'KIND_GOODY_HUT'),
    -- tech boosts and grants
    ('GOODYHUT_TECHS', 'KIND_GOODY_HUT');

-- new Buildings
REPLACE INTO Buildings
    (BuildingType, Name, Description, PrereqDistrict, PrereqTech, PurchaseYield, Cost, Entertainment, Maintenance, InternalOnly, AdvisorType)
VALUES
    -- Secrets : amenities villager totem
    ('BUILDING_AMENITIES_TOTEM_LOCKED', 'LOC_BUILDING_AMENITIES_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_AMENITIES_TOTEM', 'LOC_BUILDING_AMENITIES_TOTEM_NAME', 'LOC_BUILDING_AMENITIES_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 4, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_AMENITIES_TOTEM_BIG', 'LOC_BUILDING_AMENITIES_TOTEM_NAME', 'LOC_BUILDING_AMENITIES_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 4, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : culture villager totem
    ('BUILDING_CULTURE_TOTEM_LOCKED', 'LOC_BUILDING_CULTURE_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_CULTURE_TOTEM', 'LOC_BUILDING_CULTURE_TOTEM_NAME', 'LOC_BUILDING_CULTURE_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_CULTURE_TOTEM_BIG', 'LOC_BUILDING_CULTURE_TOTEM_NAME', 'LOC_BUILDING_CULTURE_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : faith villager totem
    ('BUILDING_FAITH_TOTEM_LOCKED', 'LOC_BUILDING_FAITH_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_FAITH_TOTEM', 'LOC_BUILDING_FAITH_TOTEM_NAME', 'LOC_BUILDING_FAITH_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_FAITH_TOTEM_BIG', 'LOC_BUILDING_FAITH_TOTEM_NAME', 'LOC_BUILDING_FAITH_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : food villager totem
    ('BUILDING_FOOD_TOTEM_LOCKED', 'LOC_BUILDING_FOOD_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_FOOD_TOTEM', 'LOC_BUILDING_FOOD_TOTEM_NAME', 'LOC_BUILDING_FOOD_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_FOOD_TOTEM_BIG', 'LOC_BUILDING_FOOD_TOTEM_NAME', 'LOC_BUILDING_FOOD_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : gold villager totem
    ('BUILDING_GOLD_TOTEM_LOCKED', 'LOC_BUILDING_GOLD_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_GOLD_TOTEM', 'LOC_BUILDING_GOLD_TOTEM_NAME', 'LOC_BUILDING_GOLD_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_GOLD_TOTEM_BIG', 'LOC_BUILDING_GOLD_TOTEM_NAME', 'LOC_BUILDING_GOLD_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : production villager totem
    ('BUILDING_PRODUCTION_TOTEM_LOCKED', 'LOC_BUILDING_PRODUCTION_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_PRODUCTION_TOTEM', 'LOC_BUILDING_PRODUCTION_TOTEM_NAME', 'LOC_BUILDING_PRODUCTION_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_PRODUCTION_TOTEM_BIG', 'LOC_BUILDING_PRODUCTION_TOTEM_NAME', 'LOC_BUILDING_PRODUCTION_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    -- Secrets : science villager totem
    ('BUILDING_SCIENCE_TOTEM_LOCKED', 'LOC_BUILDING_SCIENCE_TOTEM_LOCKED_NAME', NULL, NULL, NULL, 'YIELD_GOLD', 1000, 0, 0, 1, NULL),
    ('BUILDING_SCIENCE_TOTEM', 'LOC_BUILDING_SCIENCE_TOTEM_NAME', 'LOC_BUILDING_SCIENCE_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC'),
    ('BUILDING_SCIENCE_TOTEM_BIG', 'LOC_BUILDING_SCIENCE_TOTEM_NAME', 'LOC_BUILDING_SCIENCE_TOTEM_DESC', 'DISTRICT_CITY_CENTER', NULL, 'YIELD_GOLD', 120, 0, 1, 0, 'ADVISOR_GENERIC');

-- new BuildingConditions
REPLACE INTO BuildingConditions
    (BuildingType, UnlocksFromEffect)
VALUES
    -- Secrets : amenities villager totem 
    ('BUILDING_AMENITIES_TOTEM', 1),
    ('BUILDING_AMENITIES_TOTEM_BIG', 1),
    -- Secrets : culture villager totem 
    ('BUILDING_CULTURE_TOTEM', 1),
    ('BUILDING_CULTURE_TOTEM_BIG', 1),
    -- Secrets : faith villager totem 
    ('BUILDING_FAITH_TOTEM', 1),
    ('BUILDING_FAITH_TOTEM_BIG', 1),
    -- Secrets : food villager totem 
    ('BUILDING_FOOD_TOTEM', 1),
    ('BUILDING_FOOD_TOTEM_BIG', 1),
    -- Secrets : gold villager totem 
    ('BUILDING_GOLD_TOTEM', 1),
    ('BUILDING_GOLD_TOTEM_BIG', 1),
    -- Secrets : production villager totem 
    ('BUILDING_PRODUCTION_TOTEM', 1),
    ('BUILDING_PRODUCTION_TOTEM_BIG', 1),
    -- Secrets : science villager totem 
    ('BUILDING_SCIENCE_TOTEM', 1),
    ('BUILDING_SCIENCE_TOTEM_BIG', 1);

-- new BuildingReplaces
REPLACE INTO BuildingReplaces
    (CivUniqueBuildingType, ReplacesBuildingType)
VALUES
    -- Secrets : amenities villager totem 
    ('BUILDING_AMENITIES_TOTEM', 'BUILDING_AMENITIES_TOTEM_LOCKED'),
    ('BUILDING_AMENITIES_TOTEM_BIG', 'BUILDING_AMENITIES_TOTEM'),
    -- Secrets : culture villager totem 
    ('BUILDING_CULTURE_TOTEM', 'BUILDING_CULTURE_TOTEM_LOCKED'),
    ('BUILDING_CULTURE_TOTEM_BIG', 'BUILDING_CULTURE_TOTEM'),
    -- Secrets : faith villager totem 
    ('BUILDING_FAITH_TOTEM', 'BUILDING_FAITH_TOTEM_LOCKED'),
    ('BUILDING_FAITH_TOTEM_BIG', 'BUILDING_FAITH_TOTEM'),
    -- Secrets : food villager totem 
    ('BUILDING_FOOD_TOTEM', 'BUILDING_FOOD_TOTEM_LOCKED'),
    ('BUILDING_FOOD_TOTEM_BIG', 'BUILDING_FOOD_TOTEM'),
    -- Secrets : gold villager totem 
    ('BUILDING_GOLD_TOTEM', 'BUILDING_GOLD_TOTEM_LOCKED'),
    ('BUILDING_GOLD_TOTEM_BIG', 'BUILDING_GOLD_TOTEM'),
    -- Secrets : production villager totem 
    ('BUILDING_PRODUCTION_TOTEM', 'BUILDING_PRODUCTION_TOTEM_LOCKED'),
    ('BUILDING_PRODUCTION_TOTEM_BIG', 'BUILDING_PRODUCTION_TOTEM'),
    -- Secrets : science villager totem 
    ('BUILDING_SCIENCE_TOTEM', 'BUILDING_SCIENCE_TOTEM_LOCKED'),
    ('BUILDING_SCIENCE_TOTEM_BIG', 'BUILDING_SCIENCE_TOTEM');

-- new Building_YieldChanges
REPLACE INTO Building_YieldChanges
    (BuildingType, YieldType, YieldChange)
VALUES
    -- Secrets : culture villager totem 
    ('BUILDING_CULTURE_TOTEM', 'YIELD_CULTURE', 4),
    -- Secrets : faith villager totem
    ('BUILDING_FAITH_TOTEM', 'YIELD_FAITH', 4),
    -- Secrets : food villager totem
    ('BUILDING_FOOD_TOTEM', 'YIELD_FOOD', 4),
    -- Secrets : gold villager totem
    ('BUILDING_GOLD_TOTEM', 'YIELD_GOLD', 8),
    -- Secrets : production villager totem
    ('BUILDING_PRODUCTION_TOTEM', 'YIELD_PRODUCTION', 4),
    -- Secrets : science villager totem
    ('BUILDING_SCIENCE_TOTEM', 'YIELD_SCIENCE', 4);

-- new UnitAbilities
REPLACE INTO UnitAbilities
    (UnitAbilityType, Name, Description, Inactive, ShowFloatTextWhenEarned)
VALUES
    -- enhanced healing
    ('ABILITY_IMPROVED_HEALING', 'LOC_ABILITY_IMPROVED_HEALING_NAME', 'LOC_ABILITY_IMPROVED_HEALING_DESC', 1, 1),
    -- enhanced movement
    ('ABILITY_IMPROVED_MOVEMENT', 'LOC_ABILITY_IMPROVED_MOVEMENT_NAME', 'LOC_ABILITY_IMPROVED_MOVEMENT_DESC', 1, 1),
    -- enhanced sight
    ('ABILITY_IMPROVED_SIGHT', 'LOC_ABILITY_IMPROVED_SIGHT_NAME', 'LOC_ABILITY_IMPROVED_SIGHT_DESC', 1, 1),
    -- enhanced combat strength
    ('ABILITY_IMPROVED_STRENGTH', 'LOC_ABILITY_IMPROVED_STRENGTH_NAME', 'LOC_ABILITY_IMPROVED_STRENGTH_DESC', 1, 1);

-- new TypeTags
REPLACE INTO TypeTags
    (Type, Tag)
VALUES
    -- enhanced healing
    ('ABILITY_IMPROVED_HEALING', 'CLASS_RECON'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_MELEE'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_RANGED'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_SIEGE'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_HEAVY_CAVALRY'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_LIGHT_CAVALRY'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_ANTI_CAVALRY'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_RANGED_CAVALRY'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_HEAVY_CHARIOT'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_LIGHT_CHARIOT'),
    ('ABILITY_IMPROVED_HEALING', 'CLASS_WARRIOR_MONK'),
    -- enhanced movement
    ('ABILITY_IMPROVED_MOVEMENT', 'CLASS_ALL_UNITS'),
    -- enhanced sight
    ('ABILITY_IMPROVED_SIGHT', 'CLASS_ALL_UNITS'),
    -- enhanced combat strength
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_RECON'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_MELEE'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_RANGED'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_SIEGE'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_HEAVY_CAVALRY'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_LIGHT_CAVALRY'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_ANTI_CAVALRY'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_RANGED_CAVALRY'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_HEAVY_CHARIOT'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_LIGHT_CHARIOT'),
    ('ABILITY_IMPROVED_STRENGTH', 'CLASS_WARRIOR_MONK');

-- disable existing GoodyHuts in built-in table to allow RewardGenerator to take over
UPDATE GoodyHuts SET Weight = 0 WHERE NOT GoodyHutType = 'METEOR_GOODIES';

-- disable existing GoodyHutSubTypes in built-in table to allow RewardGenerator to take over
UPDATE GoodyHutSubTypes SET Weight = 0 WHERE NOT SubTypeGoodyHut = 'METEOR_GRANT_GOODIES';

-- dummy type for built-in table; as far as Events.GoodyHutReward is concerned, this is always the received type
REPLACE INTO GoodyHuts (GoodyHutType, Weight) VALUES ('GOODYHUT_EGHV', 100);

-- dummy reward for built-in table; as far as Events.GoodyHutReward is concerned, this is always the received reward
REPLACE INTO GoodyHutSubTypes 
    (GoodyHut, SubTypeGoodyHut, Weight, Turn, Description, ModifierID) 
VALUES 
    -- ('GOODYHUT_EGHV', 'GOODYHUT_EGHV_PLACEHOLDER', 100, 0, 'LOC_GOODYHUT_EGHV_PLACEHOLDER_DESC', 'GOODY_EGHV_DUMMY_REWARD');
    ('GOODYHUT_EGHV', 'GOODYHUT_EGHV_PLACEHOLDER', 100, 0, NULL, 'GOODY_EGHV_DUMMY_REWARD');

-- new and existing GoodyHuts for RewardGenerator
REPLACE INTO GoodyHuts_EGHV
    (GoodyHutType, Weight)
VALUES
    -- unit abilities
    ('GOODYHUT_ABILITIES', 100),
    -- civic boosts and grants
    ('GOODYHUT_CIVICS', 100),
    -- culture yields
    ('GOODYHUT_CULTURE', 100),
    -- free Envoys
    ('GOODYHUT_ENVOYS', 100),
    -- faith yields and relics
    ('GOODYHUT_FAITH', 100),
    -- new Goody Hut spawns
    ('GOODYHUT_GOODYHUTS', 100),
    -- gold yields and trade routes
    ('GOODYHUT_GOLD', 100),
    -- Hostile Villagers "rewards"
    ('GOODYHUT_HOSTILES', 100),
    -- military units
    ('GOODYHUT_MILITARY', 100),
    -- policy slots
    ('GOODYHUT_POLICIES', 100),
    -- unit experience and upgrades
    ('GOODYHUT_PROMOTIONS', 100),
    -- science yields
    ('GOODYHUT_SCIENCE', 100),
    -- Villager Totem buildings
    ('GOODYHUT_SECRETS', 100),
    -- civilian units and additional citizens
    ('GOODYHUT_SURVIVORS', 100),
    -- tech boosts and grants
    ('GOODYHUT_TECHS', 100);

-- modify the cap on experience gained from killing barbarians; default : Value = 1
UPDATE GlobalParameters SET Value = 3 WHERE Name = 'EXPERIENCE_BARB_SOFT_CAP';

-- modify the maximum level attainable by killing barbarians (units begin at Level 1); default : Value = 2
UPDATE GlobalParameters SET Value = 5 WHERE Name = 'EXPERIENCE_MAX_BARB_LEVEL';

-- modify the amount of experience gained from clearing a goody hut; default : Value = 10 (Pre XP2) | 8 (XP2 and beyond) [maybe now a hard 5 by default? fuck it]
UPDATE GlobalParameters SET Value = 3 WHERE Name = 'EXPERIENCE_ACTIVATE_GOODY_HUT';

-- adjust the frequency of, minimum distance between, and gold earned for clearing Goody Huts; defaults : TilesPerGoody = 128, GoodyRange = 3, DispersalGold = ?
UPDATE Improvements SET TilesPerGoody = 128, GoodyRange = 3, DispersalGold = 0 WHERE ImprovementType = 'IMPROVEMENT_GOODY_HUT';

-- adjust arguments for existing Faith-type "small Faith cache" reward
UPDATE ModifierArguments SET Value = 20 WHERE ModifierId = 'GOODY_FAITH_SMALL_MODIFIER' AND Name = 'Amount';    -- defaults : Value = 20

-- adjust arguments for existing Faith-type "medium Faith cache" reward
UPDATE ModifierArguments SET Value = 60 WHERE ModifierId = 'GOODY_FAITH_MEDIUM_MODIFIER' AND Name = 'Amount';   -- defaults : Value = 60

-- adjust arguments for existing Faith-type "large Faith cache" reward
UPDATE ModifierArguments SET Value = 100 WHERE ModifierId = 'GOODY_FAITH_LARGE_MODIFIER' AND Name = 'Amount';   -- defaults : Value = 100

-- adjust arguments for existing Gold-type "small Gold cache" reward
UPDATE ModifierArguments SET Value = 40 WHERE ModifierId = 'GOODY_GOLD_SMALL_MODIFIER' AND Name = 'Amount';     -- defaults : Value = 40

-- adjust arguments for existing Gold-type "medium Gold cache" reward
UPDATE ModifierArguments SET Value = 80 WHERE ModifierId = 'GOODY_GOLD_MEDIUM_MODIFIER' AND Name = 'Amount';    -- defaults : Value = 75

-- adjust arguments for existing Gold-type "large Gold cache" reward
UPDATE ModifierArguments SET Value = 120 WHERE ModifierId = 'GOODY_GOLD_LARGE_MODIFIER' AND Name = 'Amount';    -- defaults : Value = 120

-- new and existing GoodyHutSubTypes for RewardGenerator
REPLACE INTO GoodyHutSubTypes_EGHV
    (Weight, GoodyHut, MinTurn, SubTypeGoodyHut, MinOneCity, Relic, Description, OncePerEra, PrereqCivic, PrereqTech1, PrereqTech2, RequiresUnit, Experience, ExperienceMultiplier, ModifierID, Unit, UnitAbility, UnitClass, UnitType, UpgradeUnit, Hostile, Fallback)
VALUES
    -- Abilities
    (55, 'GOODYHUT_ABILITIES', 0, 'GOODYHUT_IMPROVED_SIGHT', 0, 0, 'LOC_GOODYHUT_IMPROVED_SIGHT_DESCRIPTION', 0, NULL, NULL, NULL, 1, 0, NULL, NULL, 0, 'ABILITY_IMPROVED_SIGHT', NULL, NULL, 0, 0, 0),
    (30, 'GOODYHUT_ABILITIES', 0, 'GOODYHUT_IMPROVED_HEALING', 0, 0, 'LOC_GOODYHUT_IMPROVED_HEALING_DESCRIPTION', 0, NULL, NULL, NULL, 1, 0, NULL, NULL, 0, 'ABILITY_IMPROVED_HEALING', NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_ABILITIES', 0, 'GOODYHUT_IMPROVED_MOVEMENT', 0, 0, 'LOC_GOODYHUT_IMPROVED_MOVEMENT_DESCRIPTION', 0, NULL, NULL, NULL, 1, 0, NULL, NULL, 0, 'ABILITY_IMPROVED_MOVEMENT', NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_ABILITIES', 0, 'GOODYHUT_IMPROVED_STRENGTH', 0, 0, 'LOC_GOODYHUT_IMPROVED_STRENGTH_DESCRIPTION', 0, NULL, NULL, NULL, 1, 0, NULL, NULL, 0, 'ABILITY_IMPROVED_STRENGTH', NULL, NULL, 0, 0, 0),
    -- Civics
    (55, 'GOODYHUT_CIVICS', 0, 'GOODYHUT_ONE_CIVIC_BOOST', 0, 0, 'LOC_GOODYHUT_CULTURE_ONE_CIVIC_BOOST_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_GRANT_ONE_CIVIC_BOOST', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_CIVICS', 0, 'GOODYHUT_TWO_CIVIC_BOOSTS', 0, 0, 'LOC_GOODYHUT_CULTURE_TWO_CIVIC_BOOSTS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_GRANT_TWO_CIVIC_BOOSTS', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_CIVICS', 0, 'GOODYHUT_ONE_CIVIC', 0, 0, 'LOC_GOODYHUT_CULTURE_ONE_CIVIC_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_GRANT_ONE_CIVIC', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_CIVICS', 0, 'GOODYHUT_TWO_CIVICS', 0, 0, 'LOC_GOODYHUT_CULTURE_TWO_CIVICS_DESCRIPTION', 0, 'CIVIC_CODE_OF_LAWS', NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_GRANT_TWO_CIVICS', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Culture
    (55, 'GOODYHUT_CULTURE', 0, 'GOODYHUT_SMALL_CULTURE', 0, 0, 'LOC_GOODYHUT_SMALL_CULTURE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_SMALL_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_CULTURE', 0, 'GOODYHUT_MEDIUM_CULTURE', 0, 0, 'LOC_GOODYHUT_MEDIUM_CULTURE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_MEDIUM_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_CULTURE', 0, 'GOODYHUT_LARGE_CULTURE', 0, 0, 'LOC_GOODYHUT_LARGE_CULTURE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_LARGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_CULTURE', 0, 'GOODYHUT_HUGE_CULTURE', 0, 0, 'LOC_GOODYHUT_HUGE_CULTURE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_HUGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Envoys
    (55, 'GOODYHUT_ENVOYS', 0, 'GOODYHUT_ONE_ENVOY', 0, 0, 'LOC_GOODYHUT_ENVOYS_GRANT_ONE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_ENVOYS_GRANT_ONE', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_ENVOYS', 0, 'GOODYHUT_TWO_ENVOYS', 0, 0, 'LOC_GOODYHUT_ENVOYS_GRANT_TWO_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_ENVOYS_GRANT_TWO', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_ENVOYS', 0, 'GOODYHUT_THREE_ENVOYS', 0, 0, 'LOC_GOODYHUT_ENVOYS_GRANT_THREE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_ENVOYS_GRANT_THREE', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_ENVOYS', 0, 'GOODYHUT_FOUR_ENVOYS', 0, 0, 'LOC_GOODYHUT_ENVOYS_GRANT_FOUR_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_ENVOYS_GRANT_FOUR', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Faith
    (55, 'GOODYHUT_FAITH', 0, 'GOODYHUT_SMALL_FAITH', 0, 0, 'LOC_GOODYHUT_SMALL_FAITH_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_FAITH_SMALL_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_FAITH', 0, 'GOODYHUT_MEDIUM_FAITH', 0, 0, 'LOC_GOODYHUT_MEDIUM_FAITH_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_FAITH_MEDIUM_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_FAITH', 0, 'GOODYHUT_LARGE_FAITH', 0, 0, 'LOC_GOODYHUT_LARGE_FAITH_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_FAITH_LARGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_FAITH', 0, 'GOODYHUT_ONE_RELIC', 1, 1, 'LOC_GOODYHUT_CULTURE_RELIC_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_CULTURE_GRANT_ONE_RELIC', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Gold
    (55, 'GOODYHUT_GOLD', 0, 'GOODYHUT_SMALL_GOLD', 0, 0, 'LOC_GOODYHUT_SMALL_GOLD_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_GOLD_SMALL_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_GOLD', 0, 'GOODYHUT_MEDIUM_GOLD', 0, 0, 'LOC_GOODYHUT_MEDIUM_GOLD_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_GOLD_MEDIUM_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_GOLD', 0, 'GOODYHUT_LARGE_GOLD', 0, 0, 'LOC_GOODYHUT_LARGE_GOLD_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_GOLD_LARGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_GOLD', 0, 'GOODYHUT_ADD_TRADE_ROUTE', 1, 0, 'LOC_GOODYHUT_ADD_TRADE_ROUTE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_GOLD_ADD_TRADE_ROUTE', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Goody Huts
    (55, 'GOODYHUT_GOODYHUTS', 0, 'GOODYHUT_ONE_GOODYHUT', 0, 0, 'LOC_GOODYHUT_GOODYHUTS_PLACE_ONE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_GOODYHUTS', 0, 'GOODYHUT_TWO_GOODYHUTS', 0, 0, 'LOC_GOODYHUT_GOODYHUTS_PLACE_TWO_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_GOODYHUTS', 0, 'GOODYHUT_THREE_GOODYHUTS', 0, 0, 'LOC_GOODYHUT_GOODYHUTS_PLACE_THREE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_GOODYHUTS', 0, 'GOODYHUT_FOUR_GOODYHUTS', 0, 0, 'LOC_GOODYHUT_GOODYHUTS_PLACE_FOUR_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 0, 0),
    -- Great People
    -- Hostiles
    (55, 'GOODYHUT_HOSTILES', 0, 'GOODYHUT_LOW_HOSTILITY_VILLAGERS', 0, 0, 'LOC_GOODYHUT_LOW_HOSTILITY_VILLAGERS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 1, 0),
    (30, 'GOODYHUT_HOSTILES', 0, 'GOODYHUT_MID_HOSTILITY_VILLAGERS', 0, 0, 'LOC_GOODYHUT_MID_HOSTILITY_VILLAGERS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 1, 0),
    (10, 'GOODYHUT_HOSTILES', 0, 'GOODYHUT_HIGH_HOSTILITY_VILLAGERS', 0, 0, 'LOC_GOODYHUT_HIGH_HOSTILITY_VILLAGERS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 1, 0),
    (5, 'GOODYHUT_HOSTILES', 0, 'GOODYHUT_MAX_HOSTILITY_VILLAGERS', 0, 0, 'LOC_GOODYHUT_MAX_HOSTILITY_VILLAGERS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, 0, 1, 0),
    -- Military
    (55, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_SCOUT', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_UNIT_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_SCOUT', 1, NULL, 'Recon', NULL, 0, 0, 1),
    (30, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_WARRIOR', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_MELEE_UNIT_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_WARRIOR', 1, NULL, 'Melee', NULL, 0, 0, 0),
    (30, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_SLINGER', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_RANGED_UNIT_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_SLINGER', 1, NULL, 'Ranged', NULL, 0, 0, 0),
    (30, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_SPEARMAN', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_ANTI_CAVALRY_UNIT_DESCRIPTION', 0, NULL, 'TECH_BRONZE_WORKING', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_SPEARMAN', 1, NULL, 'AntiCavalry', NULL, 0, 0, 0),
    (10, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_HEAVY_CHARIOT', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_HEAVY_CAVALRY_UNIT_DESCRIPTION', 0, NULL, 'TECH_THE_WHEEL', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_HEAVY_CHARIOT', 1, NULL, 'HeavyCavalry', NULL, 0, 0, 0),
    (10, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_HORSEMAN', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_LIGHT_CAVALRY_UNIT_DESCRIPTION', 0, NULL, 'TECH_HORSEBACK_RIDING', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_HORSEMAN', 1, NULL, 'LightCavalry', NULL, 0, 0, 0),
    (5, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_BATTERING_RAM', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_BATTERING_RAM_DESCRIPTION', 0, NULL, 'TECH_MASONRY', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_BATTERING_RAM', 1, NULL, 'Support', NULL, 0, 0, 0),
    (5, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_CATAPULT', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_CATAPULT_DESCRIPTION', 0, NULL, 'TECH_ENGINEERING', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_CATAPULT', 1, NULL, 'Siege', NULL, 0, 0, 0),
    (5, 'GOODYHUT_MILITARY', 0, 'GOODYHUT_GRANT_MILITARY_ENGINEER', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_MILITARY_ENGINEER_DESCRIPTION', 0, NULL, 'TECH_MILITARY_ENGINEERING', NULL, 0, 0, NULL, 'GOODY_MILITARY_GRANT_MILITARY_ENGINEER', 1, NULL, NULL, 'UNIT_MILITARY_ENGINEER', 0, 0, 0),
    -- Policy Slots
    (100, 'GOODYHUT_POLICIES', 0, 'GOODYHUT_ONE_MILITARY_SLOT', 0, 0, 'LOC_GOODYHUT_POLICIES_ONE_MILITARY_SLOT_DESCRIPTION', 1, 'CIVIC_POLITICAL_PHILOSOPHY', NULL, NULL, 0, 0, NULL, 'GOODY_MILITARY_POLICY_SLOT', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_POLICIES', 0, 'GOODYHUT_ONE_ECONOMIC_SLOT', 0, 0, 'LOC_GOODYHUT_POLICIES_ONE_ECONOMIC_SLOT_DESCRIPTION', 1, 'CIVIC_POLITICAL_PHILOSOPHY', NULL, NULL, 0, 0, NULL, 'GOODY_ECONOMIC_POLICY_SLOT', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_POLICIES', 0, 'GOODYHUT_ONE_DIPLOMATIC_SLOT', 0, 0, 'LOC_GOODYHUT_POLICIES_ONE_DIPLOMATIC_SLOT_DESCRIPTION', 1, 'CIVIC_DIPLOMATIC_SERVICE', NULL, NULL, 0, 0, NULL, 'GOODY_DIPLOMATIC_POLICY_SLOT', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_POLICIES', 0, 'GOODYHUT_ONE_WILDCARD_SLOT', 0, 0, 'LOC_GOODYHUT_POLICIES_ONE_WILDCARD_SLOT_DESCRIPTION', 1, 'CIVIC_POLITICAL_PHILOSOPHY', NULL, NULL, 0, 0, NULL, 'GOODY_WILDCARD_POLICY_SLOT', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Promotions
    (55, 'GOODYHUT_PROMOTIONS', 0, 'GOODYHUT_SMALL_EXPERIENCE', 0, 0, 'LOC_GOODYHUT_SMALL_EXPERIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 1, 1, 0.25, 'GOODY_EXPERIENCE_SMALL_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (30, 'GOODYHUT_PROMOTIONS', 0, 'GOODYHUT_MEDIUM_EXPERIENCE', 0, 0, 'LOC_GOODYHUT_MEDIUM_EXPERIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 1, 1, 0.5, 'GOODY_EXPERIENCE_MEDIUM_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_PROMOTIONS', 0, 'GOODYHUT_LARGE_EXPERIENCE', 0, 0, 'LOC_GOODYHUT_LARGE_EXPERIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 1, 1, 0.75, 'GOODY_EXPERIENCE_LARGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_PROMOTIONS', 0, 'GOODYHUT_HUGE_EXPERIENCE', 0, 0, 'LOC_GOODYHUT_HUGE_EXPERIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 1, 1, 1.0, 'GOODY_EXPERIENCE_HUGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_PROMOTIONS', 0, 'GOODYHUT_GRANT_UPGRADE', 0, 0, 'LOC_GOODYHUT_MILITARY_GRANT_UPGRADE_DESCRIPTION', 0, NULL, NULL, NULL, 1, 0, NULL, NULL, 0, NULL, NULL, NULL, 1, 0, 0),
    -- Science
    (55, 'GOODYHUT_SCIENCE', 0, 'GOODYHUT_SMALL_SCIENCE', 0, 0, 'LOC_GOODYHUT_SMALL_SCIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_SMALL_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_SCIENCE', 0, 'GOODYHUT_MEDIUM_SCIENCE', 0, 0, 'LOC_GOODYHUT_MEDIUM_SCIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_MEDIUM_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_SCIENCE', 0, 'GOODYHUT_LARGE_SCIENCE', 0, 0, 'LOC_GOODYHUT_LARGE_SCIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_LARGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_SCIENCE', 0, 'GOODYHUT_HUGE_SCIENCE', 0, 0, 'LOC_GOODYHUT_HUGE_SCIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_HUGE_MODIFIER', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Secrets
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_AMENITIES', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_AMENITIES_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_AMENITIES_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_CULTURE', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_CULTURE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_CULTURE_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_FAITH', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_FAITH_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_FAITH_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_FOOD', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_FOOD_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_FOOD_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_GOLD', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_GOLD_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_GOLD_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_PRODUCTION', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_PRODUCTION_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_PRODUCTION_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    (100, 'GOODYHUT_SECRETS', 0, 'GOODYHUT_VILLAGER_SECRETS_SCIENCE', 1, 0, 'LOC_GOODYHUT_VILLAGER_SECRETS_SCIENCE_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'VILLAGER_SECRETS_UNLOCK_SCIENCE_TOTEM', 0, NULL, NULL, NULL, 0, 0, 0),
    -- Survivors
    (55, 'GOODYHUT_SURVIVORS', 0, 'GOODYHUT_ADD_POP', 1, 0, 'LOC_GOODYHUT_SURVIVORS_ADD_POP_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SURVIVORS_ADD_POPULATION', 0, NULL, NULL, NULL, 0, 0, 0),
    (30, 'GOODYHUT_SURVIVORS', 0, 'GOODYHUT_GRANT_BUILDER', 1, 0, 'LOC_GOODYHUT_SURVIVORS_GRANT_BUILDER_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SURVIVORS_GRANT_BUILDER', 1, NULL, NULL, 'UNIT_BUILDER', 0, 0, 0),
    (10, 'GOODYHUT_SURVIVORS', 0, 'GOODYHUT_GRANT_TRADER', 1, 0, 'LOC_GOODYHUT_SURVIVORS_GRANT_TRADER_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SURVIVORS_GRANT_TRADER', 1, NULL, NULL, 'UNIT_TRADER', 0, 0, 0),
    (5, 'GOODYHUT_SURVIVORS', 0, 'GOODYHUT_GRANT_SETTLER', 0, 0, 'LOC_GOODYHUT_SURVIVORS_GRANT_SETTLER_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SURVIVORS_GRANT_SETTLER', 1, NULL, NULL, 'UNIT_SETTLER', 0, 0, 0),
    -- Techs
    (55, 'GOODYHUT_TECHS', 0, 'GOODYHUT_ONE_TECH_BOOST', 0, 0, 'LOC_GOODYHUT_SCIENCE_ONE_TECH_BOOST_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_GRANT_ONE_TECH_BOOST', 0, NULL, NULL, NULL, 0, 0, 1),
    (30, 'GOODYHUT_TECHS', 0, 'GOODYHUT_TWO_TECH_BOOSTS', 0, 0, 'LOC_GOODYHUT_SCIENCE_TWO_TECH_BOOSTS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_GRANT_TWO_TECH_BOOSTS', 0, NULL, NULL, NULL, 0, 0, 0),
    (10, 'GOODYHUT_TECHS', 0, 'GOODYHUT_ONE_TECH', 0, 0, 'LOC_GOODYHUT_SCIENCE_ONE_TECH_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_GRANT_ONE_TECH', 0, NULL, NULL, NULL, 0, 0, 0),
    (5, 'GOODYHUT_TECHS', 0, 'GOODYHUT_TWO_TECHS', 0, 0, 'LOC_GOODYHUT_SCIENCE_TWO_TECHS_DESCRIPTION', 0, NULL, NULL, NULL, 0, 0, NULL, 'GOODY_SCIENCE_GRANT_TWO_TECHS', 0, NULL, NULL, NULL, 0, 0, 0);

-- new Modifiers
REPLACE INTO Modifiers
    (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES
    -- Dummy modifier. It does absolutely nothing. For use by rewards implemented via lua
    ('GOODY_EGHV_DUMMY_REWARD', 'MODIFIER_PLAYER_ADJUST_YIELD_CHANGE', 1, 1, NULL),
    -- Abilities
    ('GOODY_ABILITIES_IMPROVED_SIGHT', 'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT', 0, 0, NULL),
    ('GOODY_ABILITIES_IMPROVED_HEALING', 'MODIFIER_PLAYER_UNIT_ADJUST_HEAL_PER_TURN', 0, 0, NULL),
    ('GOODY_ABILITIES_IMPROVED_MOVEMENT', 'MODIFIER_PLAYER_UNIT_ADJUST_MOVEMENT', 0, 0, NULL),
    ('GOODY_ABILITIES_IMPROVED_STRENGTH', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH', 0, 0, NULL),
    -- Civics
    ('GOODY_CULTURE_GRANT_ONE_CIVIC', 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC', 1, 1, NULL),
    ('GOODY_CULTURE_GRANT_TWO_CIVICS', 'MODIFIER_PLAYER_GRANT_RANDOM_CIVIC', 1, 1, NULL),
    -- Culture
    ('GOODY_CULTURE_SMALL_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_CULTURE_MEDIUM_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_CULTURE_LARGE_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_CULTURE_HUGE_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    -- Envoys
    ('GOODY_ENVOYS_GRANT_ONE', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 1, 1, NULL),
    ('GOODY_ENVOYS_GRANT_TWO', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 1, 1, NULL),
    ('GOODY_ENVOYS_GRANT_THREE', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 1, 1, NULL),
    ('GOODY_ENVOYS_GRANT_FOUR', 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 1, 1, NULL),
    -- Gold
    ('GOODY_GOLD_ADD_TRADE_ROUTE', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 1, 1, NULL),
    -- Goody Huts
    -- Great People
    -- Military 
    ('GOODY_MILITARY_GRANT_BATTERING_RAM', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_CATAPULT', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_HEAVY_CHARIOT', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_HORSEMAN', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_MILITARY_ENGINEER', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_SCOUT', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_SLINGER', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_SPEARMAN', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    ('GOODY_MILITARY_GRANT_WARRIOR', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_BY_CLASS_IN_NEAREST_CITY', 1, 1, NULL),
    -- Policy Slots
    ('GOODY_MILITARY_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 1, 1, NULL),
    ('GOODY_ECONOMIC_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 1, 1, NULL),
    ('GOODY_DIPLOMATIC_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 1, 1, NULL),
    ('GOODY_WILDCARD_POLICY_SLOT', 'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER', 1, 1, NULL),
    -- Promotions *** 2023/10/02 these rewards now provide a variable amount of XP based on the unit's current level ***
    ('GOODY_EXPERIENCE_SMALL_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', 1, 1, NULL),
    ('GOODY_EXPERIENCE_MEDIUM_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', 1, 1, NULL),
    ('GOODY_EXPERIENCE_LARGE_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', 1, 1, NULL),
    ('GOODY_EXPERIENCE_HUGE_MODIFIER', 'MODIFIER_PLAYER_UNIT_ADJUST_GRANT_EXPERIENCE', 1, 1, NULL),
    -- Science
    ('GOODY_SCIENCE_SMALL_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_SCIENCE_MEDIUM_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_SCIENCE_LARGE_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    ('GOODY_SCIENCE_HUGE_MODIFIER', 'MODIFIER_PLAYER_GRANT_YIELD', 1, 1, NULL),
    -- Secrets
    ('VILLAGER_SECRETS_UNLOCK_AMENITIES_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_CULTURE_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_FAITH_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_FOOD_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_GOLD_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_PRODUCTION_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    ('VILLAGER_SECRETS_UNLOCK_SCIENCE_TOTEM', 'MODIFIER_PLAYER_ADJUST_VALID_BUILDING', 1, 1, NULL),
    -- Techs
    ('GOODY_SCIENCE_GRANT_TWO_TECHS', 'MODIFIER_PLAYER_GRANT_RANDOM_TECHNOLOGY', 1, 1, NULL);

-- new ModifierArguments
REPLACE INTO ModifierArguments
    (ModifierId, Name, Value, Extra)
VALUES
    -- Dummy modifier. It does absolutely nothing. For use by rewards implemented via lua
    ('GOODY_EGHV_DUMMY_REWARD', 'Amount', 0, NULL),
    ('GOODY_EGHV_DUMMY_REWARD', 'YieldType', 'YIELD_FOOD', NULL),
    ('GOODY_EGHV_DUMMY_REWARD', 'Scale', 0, NULL),
    -- Abilities
    ('GOODY_ABILITIES_IMPROVED_SIGHT', 'Amount', 1, NULL),
    ('GOODY_ABILITIES_IMPROVED_HEALING', 'Amount', 25, NULL),
    ('GOODY_ABILITIES_IMPROVED_HEALING', 'Type', 'ALL', NULL),
    ('GOODY_ABILITIES_IMPROVED_MOVEMENT', 'Amount', 1, NULL),
    ('GOODY_ABILITIES_IMPROVED_STRENGTH', 'Amount', 10, NULL),
    -- Civics
    ('GOODY_CULTURE_GRANT_ONE_CIVIC', 'Amount', 1, -1),
    ('GOODY_CULTURE_GRANT_TWO_CIVICS', 'Amount', 2, -1),
    -- Culture
    ('GOODY_CULTURE_SMALL_MODIFIER', 'YieldType', 'YIELD_CULTURE', NULL),
    ('GOODY_CULTURE_SMALL_MODIFIER', 'Amount', 5, NULL),
    ('GOODY_CULTURE_SMALL_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_CULTURE_MEDIUM_MODIFIER', 'YieldType', 'YIELD_CULTURE', NULL),
    ('GOODY_CULTURE_MEDIUM_MODIFIER', 'Amount', 10, NULL),
    ('GOODY_CULTURE_MEDIUM_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_CULTURE_LARGE_MODIFIER', 'YieldType', 'YIELD_CULTURE', NULL),
    ('GOODY_CULTURE_LARGE_MODIFIER', 'Amount', 15, NULL),
    ('GOODY_CULTURE_LARGE_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_CULTURE_HUGE_MODIFIER', 'YieldType', 'YIELD_CULTURE', NULL),
    ('GOODY_CULTURE_HUGE_MODIFIER', 'Amount', 25, NULL),
    ('GOODY_CULTURE_HUGE_MODIFIER', 'Scale', 1, NULL),
    -- Envoys
    ('GOODY_ENVOYS_GRANT_ONE', 'Amount', 1, NULL),
    ('GOODY_ENVOYS_GRANT_TWO', 'Amount', 2, NULL),
    ('GOODY_ENVOYS_GRANT_THREE', 'Amount', 3, NULL),
    ('GOODY_ENVOYS_GRANT_FOUR', 'Amount', 4, NULL),
    -- Gold
    ('GOODY_GOLD_ADD_TRADE_ROUTE', 'Amount', 1, NULL),
    -- Goody Huts
    -- Great People
    -- Military
    ('GOODY_MILITARY_GRANT_BATTERING_RAM', 'UnitPromotionClassType', 'PROMOTION_CLASS_SUPPORT', NULL),
    ('GOODY_MILITARY_GRANT_CATAPULT', 'UnitPromotionClassType', 'PROMOTION_CLASS_SIEGE', NULL),
    ('GOODY_MILITARY_GRANT_HEAVY_CHARIOT', 'UnitPromotionClassType', 'PROMOTION_CLASS_HEAVY_CAVALRY', NULL),
    ('GOODY_MILITARY_GRANT_HORSEMAN', 'UnitPromotionClassType', 'PROMOTION_CLASS_LIGHT_CAVALRY', NULL),
    ('GOODY_MILITARY_GRANT_MILITARY_ENGINEER', 'UnitType', 'UNIT_MILITARY_ENGINEER', NULL),
    ('GOODY_MILITARY_GRANT_MILITARY_ENGINEER', 'Amount', 1, NULL),
    ('GOODY_MILITARY_GRANT_SCOUT', 'UnitPromotionClassType', 'PROMOTION_CLASS_RECON', NULL),
    ('GOODY_MILITARY_GRANT_SLINGER', 'UnitPromotionClassType', 'PROMOTION_CLASS_RANGED', NULL),
    ('GOODY_MILITARY_GRANT_SPEARMAN', 'UnitPromotionClassType', 'PROMOTION_CLASS_ANTI_CAVALRY', NULL),
    ('GOODY_MILITARY_GRANT_WARRIOR', 'UnitPromotionClassType', 'PROMOTION_CLASS_MELEE', NULL),
    -- Policy Slots
    ('GOODY_MILITARY_POLICY_SLOT', 'GovernmentSlotType', 'SLOT_MILITARY', NULL),
    ('GOODY_ECONOMIC_POLICY_SLOT', 'GovernmentSlotType', 'SLOT_ECONOMIC', NULL),
    ('GOODY_DIPLOMATIC_POLICY_SLOT', 'GovernmentSlotType', 'SLOT_DIPLOMATIC', NULL),
    ('GOODY_WILDCARD_POLICY_SLOT', 'GovernmentSlotType', 'SLOT_WILDCARD', NULL),
    -- Promotions *** 2023/10/02 these rewards now provide a variable amount of XP based on the unit's current level ***
    ('GOODY_EXPERIENCE_SMALL_MODIFIER', 'Amount', 3, NULL),
    ('GOODY_EXPERIENCE_MEDIUM_MODIFIER', 'Amount', 7, NULL),
    ('GOODY_EXPERIENCE_LARGE_MODIFIER', 'Amount', 11, NULL),
    ('GOODY_EXPERIENCE_HUGE_MODIFIER', 'Amount', 15, NULL),
    -- Science
    ('GOODY_SCIENCE_SMALL_MODIFIER', 'YieldType', 'YIELD_SCIENCE', NULL),
    ('GOODY_SCIENCE_SMALL_MODIFIER', 'Amount', 5, NULL),
    ('GOODY_SCIENCE_SMALL_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_SCIENCE_MEDIUM_MODIFIER', 'YieldType', 'YIELD_SCIENCE', NULL),
    ('GOODY_SCIENCE_MEDIUM_MODIFIER', 'Amount', 10, NULL),
    ('GOODY_SCIENCE_MEDIUM_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_SCIENCE_LARGE_MODIFIER', 'YieldType', 'YIELD_SCIENCE', NULL),
    ('GOODY_SCIENCE_LARGE_MODIFIER', 'Amount', 15, NULL),
    ('GOODY_SCIENCE_LARGE_MODIFIER', 'Scale', 1, NULL),
    ('GOODY_SCIENCE_HUGE_MODIFIER', 'YieldType', 'YIELD_SCIENCE', NULL),
    ('GOODY_SCIENCE_HUGE_MODIFIER', 'Amount', 25, NULL),
    ('GOODY_SCIENCE_HUGE_MODIFIER', 'Scale', 1, NULL),
    -- Secrets
    ('VILLAGER_SECRETS_UNLOCK_AMENITIES_TOTEM', 'BuildingType', 'BUILDING_AMENITIES_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_AMENITIES_TOTEM', 'BuildingTypeToReplace', 'BUILDING_AMENITIES_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_CULTURE_TOTEM', 'BuildingType', 'BUILDING_CULTURE_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_CULTURE_TOTEM', 'BuildingTypeToReplace', 'BUILDING_CULTURE_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_FAITH_TOTEM', 'BuildingType', 'BUILDING_FAITH_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_FAITH_TOTEM', 'BuildingTypeToReplace', 'BUILDING_FAITH_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_FOOD_TOTEM', 'BuildingType', 'BUILDING_FOOD_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_FOOD_TOTEM', 'BuildingTypeToReplace', 'BUILDING_FOOD_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_GOLD_TOTEM', 'BuildingType', 'BUILDING_GOLD_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_GOLD_TOTEM', 'BuildingTypeToReplace', 'BUILDING_GOLD_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_PRODUCTION_TOTEM', 'BuildingType', 'BUILDING_PRODUCTION_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_PRODUCTION_TOTEM', 'BuildingTypeToReplace', 'BUILDING_PRODUCTION_TOTEM_LOCKED', NULL),
    ('VILLAGER_SECRETS_UNLOCK_SCIENCE_TOTEM', 'BuildingType', 'BUILDING_SCIENCE_TOTEM', NULL),
    ('VILLAGER_SECRETS_UNLOCK_SCIENCE_TOTEM', 'BuildingTypeToReplace', 'BUILDING_SCIENCE_TOTEM_LOCKED', NULL),
    -- Techs
    ('GOODY_SCIENCE_GRANT_TWO_TECHS', 'Amount', 2, -1);

-- new UnitAbilityModifiers
REPLACE INTO UnitAbilityModifiers
    (UnitAbilityType, ModifierId)
VALUES
    -- enhanced healing
    ('ABILITY_IMPROVED_HEALING', 'GOODY_ABILITIES_IMPROVED_HEALING'),
    -- enhanced movement
    ('ABILITY_IMPROVED_MOVEMENT', 'GOODY_ABILITIES_IMPROVED_MOVEMENT'),
    -- enhanced sight
    ('ABILITY_IMPROVED_SIGHT', 'GOODY_ABILITIES_IMPROVED_SIGHT'),
    -- enhanced combat strength
    ('ABILITY_IMPROVED_STRENGTH', 'GOODY_ABILITIES_IMPROVED_STRENGTH');

-- new ModifierStrings
REPLACE INTO ModifierStrings
    (ModifierId, Context, Text)
VALUES
    -- enhanced healing
    ('GOODY_ABILITIES_IMPROVED_HEALING', 'Preview', '{LOC_ABILITY_IMPROVED_HEALING_DESC} {LOC_WONDER_DESCRIPTOR_PREVIEW_TEXT}'),
    -- enhanced movement
    ('GOODY_ABILITIES_IMPROVED_MOVEMENT', 'Preview', '{LOC_ABILITY_IMPROVED_MOVEMENT_DESC} {LOC_WONDER_DESCRIPTOR_PREVIEW_TEXT}'),
    -- enhanced sight
    ('GOODY_ABILITIES_IMPROVED_SIGHT', 'Preview', '{LOC_ABILITY_IMPROVED_SIGHT_DESC} {LOC_WONDER_DESCRIPTOR_PREVIEW_TEXT}'),
    -- enhanced combat strength
    ('GOODY_ABILITIES_IMPROVED_STRENGTH', 'Preview', '{LOC_ABILITY_IMPROVED_STRENGTH_DESC} {LOC_WONDER_DESCRIPTOR_PREVIEW_TEXT}');

-- unit rewards by game Era
REPLACE INTO UnitRewards
    (Era, Recon, Melee, Ranged, AntiCavalry, HeavyCavalry, LightCavalry, Siege, Support, NavalMelee, NavalRanged)
VALUES
    -- heavy chariot is "light" cavalry for ancient era so that something can be granted if resource prerequisite is not met
    (0, 'UNIT_SCOUT', 'UNIT_WARRIOR', 'UNIT_SLINGER', 'UNIT_SPEARMAN', 'UNIT_HEAVY_CHARIOT', 'UNIT_HEAVY_CHARIOT', 'UNIT_CATAPULT', 'UNIT_BATTERING_RAM', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
    (1, 'UNIT_SCOUT', 'UNIT_SWORDSMAN', 'UNIT_ARCHER', 'UNIT_SPEARMAN', 'UNIT_HEAVY_CHARIOT', 'UNIT_HORSEMAN', 'UNIT_CATAPULT', 'UNIT_BATTERING_RAM', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
    (2, 'UNIT_SCOUT', 'UNIT_MAN_AT_ARMS', 'UNIT_CROSSBOWMAN', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_HORSEMAN', 'UNIT_TREBUCHET', 'UNIT_SIEGE_TOWER', 'UNIT_GALLEY', 'UNIT_QUADRIREME'),
    (3, 'UNIT_SCOUT', 'UNIT_MUSKETMAN', 'UNIT_CROSSBOWMAN', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_HORSEMAN', 'UNIT_BOMBARD', 'UNIT_SIEGE_TOWER', 'UNIT_CARAVEL', 'UNIT_FRIGATE'),
    (4, 'UNIT_RANGER', 'UNIT_LINE_INFANTRY', 'UNIT_FIELD_CANNON', 'UNIT_PIKEMAN', 'UNIT_KNIGHT', 'UNIT_CAVALRY', 'UNIT_BOMBARD', 'UNIT_MEDIC', 'UNIT_IRONCLAD', 'UNIT_FRIGATE'),
    (5, 'UNIT_RANGER', 'UNIT_INFANTRY', 'UNIT_FIELD_CANNON', 'UNIT_AT_CREW', 'UNIT_TANK', 'UNIT_CAVALRY', 'UNIT_ARTILLERY', 'UNIT_MEDIC', 'UNIT_IRONCLAD', 'UNIT_BATTLESHIP'),
    (6, 'UNIT_RANGER', 'UNIT_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_AT_CREW', 'UNIT_TANK', 'UNIT_HELICOPTER', 'UNIT_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_BATTLESHIP'),
    (7, 'UNIT_RANGER', 'UNIT_MECHANIZED_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_MODERN_AT', 'UNIT_MODERN_ARMOR', 'UNIT_HELICOPTER', 'UNIT_ROCKET_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_MISSILE_CRUISER'),
    (8, 'UNIT_RANGER', 'UNIT_MECHANIZED_INFANTRY', 'UNIT_MACHINE_GUN', 'UNIT_MODERN_AT', 'UNIT_MODERN_ARMOR', 'UNIT_HELICOPTER', 'UNIT_ROCKET_ARTILLERY', 'UNIT_MEDIC', 'UNIT_DESTROYER', 'UNIT_MISSILE_CRUISER');

-- combat experience values for promotions-type rewards; XPFNL = total XP for next level, XPTNL = XP from previous level to next level
REPLACE INTO PromotionLevels
    (XPFNL, Level, XPTNL)
VALUES
    (15, 1, 15),
    (45, 2, 30),
    (90, 3, 45),
    (150, 4, 60),
    (225, 5, 75),
    (315, 6, 90),
    (420, 7, 105);

-- increased hostility targets
REPLACE INTO IncreasedHostilityTargets
	(UnitType)
SELECT UnitType FROM Units
WHERE FormationClass = 'FORMATION_CLASS_CIVILIAN' AND NOT (UnitType = 'UNIT_ARCHAEOLOGIST' OR UnitType = 'UNIT_NATURALIST' OR UnitType = 'UNIT_ROCK_BAND' OR UnitType = 'UNIT_SPY');

-- decreased hostility targets
REPLACE INTO DecreasedHostilityTargets
	(PromotionClass)
SELECT PromotionClass FROM Units
WHERE FormationClass = 'FORMATION_CLASS_LAND_COMBAT' AND NOT PromotionClass = 'PROMOTION_CLASS_RECON';

/* ###########################################################################
    End EGHV ingame configuration
########################################################################### */
